<!DOCTYPE html>
<div id="kontajner">
  <div id="hlavicka">
    <div class="logo"> <img src="public/images/logo_ompi.jpg" width="80" height="100"> </div>
    <div class="title">ODDELENIE METÓDY PACHOVEJ IDENTIFIKÁCIE</div>
  </div>
</div>
<div class="menu-container" align="center">
<div id="menu">
  <div class="dropdown">
      <button class="dropbtn"> <a href="index.php">DOMOV</a> </button>
    </div>
    <div class="dropdown">
      <button class="dropbtn"> <a href="kontakt.php">KONTAKT</a> </button>
  	</div>
     <div class="dropdown">
     	<button class="dropbtn">TECHNICI</button>
    <div class="dropdown-content"> <a href="technici-hladat.php">VYHĽADAŤ</a> <a href="technici-zapis.php">ZÁPIS UDALOSTI</a> </div>
  </div>
  <div class="dropdown">
    <button class="dropbtn">INFORMÁCIE PRE OČTK</button>
    <div class="dropdown-content"> <a href="./info-pre-octk.php">VYHĽADAŤ PODĽA ČVS</a> <a href="./hladaj_pps.php">VYHĽADAŤ OSOBU</a> </div>
  </div>
  <div class="dropdown">
    <button class="dropbtn">PACHOVÉ STOPY</button>
    <div class="dropdown-content"> <a href="./hladaj_ps-ompi.php">NAČÍTAŤ NOVÚ</a> <a href="#">OPRAVA</a> <a href="#">OSTATNÉ</a> </div>
  </div>
  <div class="dropdown">
    <button class="dropbtn">POROVNÁVACIE PACHOVÉ STOPY</button>
  <div class="dropdown-content"> <a href="./hladaj_pps-ompi.php">NAČÍTAŤ NOVÚ</a> <a href="porovnavacie-pachove-stopy-oprava">OPRAVA</a> <a href="#">OSTATNÉ</a> </div>
  </div>
  <div class="dropdown">
    <button class="dropbtn">PACHOVÁ IDENTIFIKÁCIA</button>
  <div class="dropdown-content"> <a href="./zapis-pi.php">ZÁPIS</a> <a href="#">TLAČ PROTOKOLU</a> <a href="#">VYHĽADANIE</a>
    <a href="stat.xlsx">ŠTATISTIKA</a></div>
  </div>
</div>
